apiVersion: v1
kind: Secret
metadata:
  name: bear-secrets
  namespace: bear-erp
type: Opaque
data:
  # Base64 encoded - SUBSTITUIR EM PRODUÇÃO
  mongo-user: YmVhcmFkbWlu
  mongo-password: QmVhckVycDIwMjQh
  jwt-secret: YmVhci1lcnAtand0LXNlY3JldC1rZXktbWluaW11bS0yNTYtYml0cy1mb3ItaG1hYy1zaGEyNTYtYWxnb3JpdGht
  aes-key: YmVhci1lcnAtYWVzLTI1Ni1rZXktMzItYnl0ZXM=
  redis-password: QmVhclJlZGlzMjAyNCE=
  mongodb-uri: bW9uZ29kYjovL2JlYXJhZG1pbjpCZWFyRXJwMjAyNCFAbW9uZ29kYjoyNzAxNy9iZWFyX2VycD9hdXRoU291cmNlPWFkbWlu
